[BMP:masks]
gynvael/zrozumiec-programowanie-cwiczenia pull request #27
Opened 2023-08-20 15:47 UTC by michal-siedlecki

2023-08-20 18:53 UTC, gynvael commented on BMP-masks/masks.py
> +    return val << (4 * bit_offset)
Nie ma potrzeby mnożyć * 4. Jak nazwa zmiennej wskazuje, to `bit_offset`, nie `nibble_offset`.

2023-08-20 18:57 UTC, gynvael commented on BMP-masks/masks.py
> +            nibbles += 1
Raczej powinno się liczyć po bitach, nie po pełnych 4-bitowych grupach. Przykładowo, 0x6 (0b110) to jest dobra maska (bit_offset 1, bits_per_color 2), ale ta funkcja wróci 1, 4. Po prostu na bitach, nie ma potrzeby mieszać nibbli do tego :)

2023-08-20 18:58 UTC, gynvael requested changes
Dwie drobne poprawki. Trochę więcej testów by się przydało, tak żeby wyłapać te wskazane błędy :)

2023-08-21 07:03 UTC, gynvael commented
Teraz wygląda dobrze :)

2023-08-21 07:03 UTC, michal-siedlecki commented
Dzięki za comment, poprawki zrobione, zastanawiam się tylko czy nie zmodyfikować jeszcze bo na przykład maska 0x5 (0b101) nie przechodzi, a chyba powinna

2023-08-21 07:03 UTC, merged

2023-08-21 07:05 UTC, gynvael commented
Nie, 0x5 nie jest poprawną maską. Maska musi być ciągła, tj. wszystkie 1 muszą być koło siebie:
```
<dowolna liczba zer><grupa jedynek><zero lub więcej zer>
00001110000 - ok
00000000001 - ok
11111111111 - ok
00000100001 - niepoprawna maska w tym kontekście
```

2023-08-21 07:06 UTC, michal-siedlecki commented
ok, rozumiem :) faktycznie. Dzięki!